### ISSUE TITLE
Broken leaflet demo at x-tags.org 

### ISSUE THREAD

**Issue by marinintim** [x-tag/core#120]
![2015-03-24t20 30 17](https://cloud.githubusercontent.com/assets/66025/6808373/a40169c4-d264-11e4-81ba-a1d0e6effc6f.png)
Not sure if I should report it here, but x-tags.org/about links "file an issue" to this repo.

Tiles are not loading, and then I click "Open in new tab", I get "Wrong apikey" message.

**Comment by techtonik** [comment]
Same problem here.

**Comment by csuwildcat** [comment]
It's because that specific tile theme provider shutdown. I need to update with the latest Leaflet, that should fix it automatically. Most of the focus is on standing up a better site on ReadMe.io: https://x-tag.readme.io/ - I have documented the lib in much more detail there.

**Comment by brylie** [comment]
Any status update here? The map is still not rendering, and this issue was reported in March.

**Comment by csuwildcat** [comment]
Update: I'm now working for Microsoft and we will be using X-Tag as our supported Web Components library. I will be completely redoing the site, and integrating all the docs that we've written on readme.io here: https://x-tag.readme.io/v1.0

As far as maps goes, there's an x-gmap tag that provides a drop-in google map, and we'll be developing a Bing map soon as well.

**Comment by csuwildcat** [comment]
The leaflet map stopped working because that tile provider is out of business, I need to update that code to use the new Leaflet default tiles.

**Comment by csuwildcat** [comment]
This has been taken care of in our move to our new project site: http://x-tag.github.io/
